version: "3"
services:
  ansible001:
    container_name: ansible001
    build:
      context: .
      dockerfile: Dockerfile.ansible
    tty: true
    networks:
      - net001
    volumes:
      - ./app:/app
    restart: always
    depends_on:
      - deb001
  deb001:
    container_name: deb001
    build:
      context: .
      dockerfile: Dockerfile.demo
    tty: true
    networks:
      - net001
    restart: always
networks:
  net001: