FROM httpd:alpine

# Apache と Tomcat を連携させるための設定を httpd.conf に追加
RUN echo 'LoadModule proxy_module modules/mod_proxy.so' >> /usr/local/apache2/conf/httpd.conf \
    && echo 'LoadModule proxy_ajp_module modules/mod_proxy_ajp.so' >> /usr/local/apache2/conf/httpd.conf \
    && echo 'ProxyPass / ajp://tomcat001:8009/' >> /usr/local/apache2/conf/httpd.conf \
    && echo 'ProxyPassReverse / ajp://tomcat001:8009/' >> /usr/local/apache2/conf/httpd.conf

ENTRYPOINT [ "httpd-foreground" ]