apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd001dep
spec:
  selector:
    matchLabels:
      app: httpd001kube
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd001kube
    spec:
      containers:
        - name: httpd001
          image: httpd
          ports:
            - containerPort: 80